<?php
return array(
    'user/activation/([a-zA-Z0-9]+)' => 'user/activation/$1',
    'user/register' => 'user/register',
    'user/login' => 'user/login',
    'user/logout' => 'user/logout',
    'cabinet/edit/name' => 'cabinet/editName',
    'cabinet/edit/password' => 'cabinet/editPassword',
    'cabinet/edit/email' => 'cabinet/editEmail',
    'cabinet/activation/([a-zA-Z0-9]+)/([a-zA-Z0-9]+)' => 'user/activation/$1/$2',
    'cabinet' => 'cabinet/index',
    'admin/consumer/distributor/add/([0-9]+)' => 'admin/ConsumerDistributorsAdd/$1',
    'admin/consumer/distributor/list/([0-9]+)' => 'admin/ConsumerDistributors/$1',
    'admin/consumer' => 'admin/showConsumers',
    'admin/distributor' => 'admin/showDistributors',
    'admin/user/([0-9]+)' => 'admin/manageUser/$1',
    'admin/user/block/([0-9]+)' => 'admin/blockUser/$1',
    'admin/user/unblock/([0-9]+)' => 'admin/unblockUser/$1',
    'admin/user/editmail/([0-9]+)' => 'admin/editUserMail/$1',
    'admin/user/editname/([0-9]+)' => 'admin/editUserName/$1',
    'admin' => 'admin/index',
    'consumer/timetable' => 'consumer/timetable',
    'consumer/create_order' => 'consumer/orderCreate',
    'consumer/order_content/([0-9]+)' => 'consumer/orderContent/$1',
    'consumer/distributors' => 'consumer/distributors',
    'consumer' => 'consumer/index',
    'distributor/orders/content/([0-9]+)' => 'distributor/orderContent/$1',
    'distributor/orders/edit/([0-9]+)' => 'distributor/orderEdit/$1',
    'distributor/orders/delete/([0-9]+)' => 'distributor/orderDelete/$1',
    'distributor/orders' => 'distributor/orderList',
    'distributor/timetable' => 'distributor/timetable',
    'distributor/consumers' => 'distributor/consumers',
    'distributor/products/delete/([0-9]+)' => 'distributor/productDelete/$1',
    'distributor/products/edit/([0-9]+)' => 'distributor/productEdit/$1',
    'distributor/products/add' => 'distributor/productAdd',
    'distributor/products' => 'distributor/products',
    'distributor' => 'distributor/index',

    'index.php' => 'cabinet/index',
    '' => 'cabinet/index',
);